# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Binary Build
on:
  pull_request:
  push:
    branches:
      - playground
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '28 6 * * *'


jobs:
  binary:
    uses: fmauch/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@parse_ici_output
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling]
        ROS_REPO: [main]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: control_toolbox-not-released.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: ros2-master
