name: Coverage Build - Rolling
on:
  workflow_dispatch:
  push:
    branches:
      - ros2-master
  pull_request:
    branches:
      - ros2-master

jobs:
  coverage_rolling:
    name: coverage build - rolling
    uses: fmauch/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@patch-1
    secrets: inherit
    with:
      ros_distro: rolling
